SPHINXOPTS  ?=
SPHINXBUILD ?= sphinx-build
SOURCEDIR    = source
BUILDDIR     = build

.PHONY: default
default: html

.PHONY: html
html:
	$(SPHINXBUILD) -b html "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS)

