name: coverage

on:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      env:
        SKBUILD_CMAKE_BUILD_TYPE: Debug
        SKBUILD_BUILD_DIR: build/coverage
        SKBUILD_CMAKE_DEFINE: BUILD_COVERAGE=ON
      run: |
        python -m pip install --upgrade pip
        pip install scikit-build-core nanobind
        pip install --no-build-isolation -ve .
        pip install --no-build-isolation -ve '.[test,coverage]'
    - name: Run tests
      run: |
        coverage run -m pytest -vv
    - name: Generate coverage
      run: |
        cpp-coveralls --include src --include tests --dump cpp-coveralls.json
        python3 -m coveralls --merge cpp-coveralls.json --output coveralls.json
    - name: Upload coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        coveralls --submit coveralls.json
